src/main/java/com/mps/think/setup/repo/CreditStatusRepo.java
src/main/java/com/mps/think/setup/serviceImpl/CreditStatusServiceImpl.java
src/main/java/com/mps/think/setup/serviceImpl/CustomerCategoryServiceImpl.java
src/main/java/com/mps/think/setup/serviceImpl/ProfitCenterServiceImpl.java
src/main/java/com/mps/think/setup/serviceImpl/PublisherSerivceImpl.java
src/main/java/com/mps/think/setup/serviceImpl/RentalStatusServiceImpl.java
src/main/java/com/mps/think/setup/serviceImpl/SalesRepresentativeServiceImp.java
src/main/java/com/mps/think/setup/serviceImpl/VolumeGroupServiceImpl.java

Reverts highwire/think-setup#3

Revert "exception handling"

---

src/main/java/com/mps/think/setup/controller/SourceFormatSegmentController.java
src/main/java/com/mps/think/setup/model/SourceFormatSegment.java
src/main/java/com/mps/think/setup/serviceImpl/SourceFormatSegmentServiceImpl.java
src/main/java/com/mps/think/setup/vo/SourceFormatSegmentVo.java

main to THW-124 new

---

src/main/java/com/mps/think/setup/controller/OrderCategoryController.java
src/main/java/com/mps/think/setup/model/OrderCategory.java
src/main/java/com/mps/think/setup/repo/OrderCategoryRepo.java
src/main/java/com/mps/think/setup/service/OrderCategoryService.java
src/main/java/com/mps/think/setup/serviceImpl/OrderCategoryServiceImpl.java
src/main/java/com/mps/think/setup/vo/OrderCategoryVo.java

Main  <-   Thw 124new 

---

src/main/java/com/mps/think/setup/controller/SpecialTaxIdsController.java
src/main/java/com/mps/think/setup/model/SpecialTaxIds.java
src/main/java/com/mps/think/setup/repo/SpecialTaxIdsRepo.java
src/main/java/com/mps/think/setup/service/SpecialTaxIdsService.java
src/main/java/com/mps/think/setup/serviceImpl/SpecialTaxIdsServiceImpl.java
src/main/java/com/mps/think/setup/vo/SpecialTaxIdsVO.java

THW-149 commiting

---

src/main/java/com/mps/think/setup/controller/JurisdictionsController.java
src/main/java/com/mps/think/setup/model/Jurisdictions.java
src/main/java/com/mps/think/setup/repo/JurisdictionsRepo.java
src/main/java/com/mps/think/setup/service/JurisdictionsService.java
src/main/java/com/mps/think/setup/serviceImpl/JurisdictionsServiceImpl.java
src/main/java/com/mps/think/setup/vo/JurisdictionsVO.java

Jurisdictions

---

src/main/java/com/mps/think/setup/controller/SubscriptionCategoriesController.java
src/main/java/com/mps/think/setup/model/SubscriptionCategories.java
src/main/java/com/mps/think/setup/repo/SubscriptionCategoriesRepo.java
src/main/java/com/mps/think/setup/service/SubscriptionCategoriesService.java
src/main/java/com/mps/think/setup/serviceImpl/SubscriptionCategoriesServiceImpl.java
src/main/java/com/mps/think/setup/vo/SubscriptionCategoriesVO.java

added publisher id

---

src/main/java/com/mps/think/setup/model/CommodityCodes.java

changes in table name

---

src/main/java/com/mps/think/setup/controller/DeliveryMethodOverridesController.java
src/main/java/com/mps/think/setup/controller/DeliveryMethodsController.java
src/main/java/com/mps/think/setup/controller/ShippingMethodController.java
src/main/java/com/mps/think/setup/controller/ShippingPriceListController.java
src/main/java/com/mps/think/setup/controller/TransportModeController.java
src/main/java/com/mps/think/setup/model/DeliveryMethodOverrides.java
src/main/java/com/mps/think/setup/model/DeliveryMethods.java
src/main/java/com/mps/think/setup/model/ShippingMethod.java
src/main/java/com/mps/think/setup/model/ShippingPriceList.java
src/main/java/com/mps/think/setup/model/TransportMode.java
src/main/java/com/mps/think/setup/repo/DeliveryMethodOverridesRepo.java
src/main/java/com/mps/think/setup/repo/DeliveryMethodsRepo.java
src/main/java/com/mps/think/setup/repo/ShippingMethodRepo.java
src/main/java/com/mps/think/setup/repo/ShippingPriceListRepo.java
src/main/java/com/mps/think/setup/repo/TransportModeRepo.java
src/main/java/com/mps/think/setup/service/DeliveryMethodOverridesService.java
src/main/java/com/mps/think/setup/service/DeliveryMethodsService.java
src/main/java/com/mps/think/setup/service/ShippingMethodService.java
src/main/java/com/mps/think/setup/service/ShippingPriceListService.java
src/main/java/com/mps/think/setup/service/TransportModeService.java
src/main/java/com/mps/think/setup/serviceImpl/DeliveryMethodOverridesServiceImpl.java
src/main/java/com/mps/think/setup/serviceImpl/DeliveryMethodsServiceImpl.java
src/main/java/com/mps/think/setup/serviceImpl/ShippingMethodServiceImpl.java
src/main/java/com/mps/think/setup/serviceImpl/ShippingPriceListImpl.java
src/main/java/com/mps/think/setup/serviceImpl/TransportModeServiceImpl.java
src/main/java/com/mps/think/setup/vo/DeliveryMethodOverridesVO.java
src/main/java/com/mps/think/setup/vo/DeliveryMethodsVO.java
src/main/java/com/mps/think/setup/vo/ShippingMethodVO.java
src/main/java/com/mps/think/setup/vo/ShippingPriceListVO.java
src/main/java/com/mps/think/setup/vo/TransportModeVO.java

completed THW-141 to THW-145

---

src/main/java/com/mps/think/setup/controller/SubscriptionCategoryController.java
src/main/java/com/mps/think/setup/model/SubscriptionCategory.java
src/main/java/com/mps/think/setup/repo/SubscriptionCategoryRepo.java
src/main/java/com/mps/think/setup/service/SubscriptionCategoryService.java
src/main/java/com/mps/think/setup/serviceImpl/SubscriptionCategoryServiceImpl.java
src/main/java/com/mps/think/setup/vo/SubscriptionCategoryVO.java

subscription categories

---

src/main/java/com/mps/think/setup/controller/OrderCategoryController.java
src/main/java/com/mps/think/setup/model/OrderCategory.java
src/main/java/com/mps/think/setup/repo/OrderCategoryRepo.java
src/main/java/com/mps/think/setup/service/OrderCategoryService.java
src/main/java/com/mps/think/setup/serviceImpl/OrderCategoryServiceImpl.java
src/main/java/com/mps/think/setup/vo/OrderCategoryVO.java

THW-124new

---

src/main/java/com/mps/think/setup/controller/RateCardsController.java
src/main/java/com/mps/think/setup/controller/RateCardsRenewalsController.java
src/main/java/com/mps/think/setup/model/RateCards.java
src/main/java/com/mps/think/setup/model/RateCardsRenewals.java
src/main/java/com/mps/think/setup/repo/RateCardsRenewalsRepo.java
src/main/java/com/mps/think/setup/repo/RateCardsRepo.java
src/main/java/com/mps/think/setup/service/RateCardsRenewalsService.java
src/main/java/com/mps/think/setup/service/RateCardsService.java
src/main/java/com/mps/think/setup/serviceImpl/RateCardsRenewalsServiceImpl.java
src/main/java/com/mps/think/setup/serviceImpl/RateCardsServiceImpl.java
src/main/java/com/mps/think/setup/vo/RateCardsRenewalsVO.java
src/main/java/com/mps/think/setup/vo/RateCardsVO.java

THW-212new

---

src/main/java/com/mps/think/setup/controller/AddressesController.java
src/main/java/com/mps/think/setup/model/Addresses.java
src/main/java/com/mps/think/setup/model/CustomerAddresses.java
src/main/java/com/mps/think/setup/model/CustomerDetails.java
src/main/java/com/mps/think/setup/repo/CustomerAddressesRepo.java
src/main/java/com/mps/think/setup/service/AddressService.java
src/main/java/com/mps/think/setup/serviceImpl/AddressesServiceImpl.java
src/main/java/com/mps/think/setup/serviceImpl/CustomerDetailsServiceImpl.java
src/main/java/com/mps/think/setup/vo/AddressesVO.java
src/main/java/com/mps/think/setup/vo/CustomerDetailsVO.java

Reverts highwire/think-setup#58

Revert "Revert "THW-12""

---

src/main/java/com/mps/think/setup/model/ParentClass.java
src/main/java/com/mps/think/setup/serviceImpl/ParentClassServiceImpl.java

Reverts highwire/think-setup#60

Revert "Thw 12"

---

src/main/java/com/mps/think/setup/model/ParentClass.java
src/main/java/com/mps/think/setup/serviceImpl/ParentClassServiceImpl.java

Reverts highwire/think-setup#61

Revert "Revert "Thw 12""

---

src/main/java/com/mps/think/setup/controller/AddOrderController.java
src/main/java/com/mps/think/setup/model/Order.java
src/main/java/com/mps/think/setup/model/OrderAddressMapping.java
src/main/java/com/mps/think/setup/model/OrderAuxiliaryInformation.java
src/main/java/com/mps/think/setup/model/OrderDeliveryOptions.java
src/main/java/com/mps/think/setup/model/OrderItems.java
src/main/java/com/mps/think/setup/model/OrderKeyInformation.java
src/main/java/com/mps/think/setup/model/PaymentBreakdown.java
src/main/java/com/mps/think/setup/repo/AddOrderRepo.java
src/main/java/com/mps/think/setup/service/AddOrderService.java
src/main/java/com/mps/think/setup/serviceImpl/AddOrderServiceImpl.java
src/main/java/com/mps/think/setup/vo/EnumModelVO.java
src/main/java/com/mps/think/setup/vo/OrderAddressMappingVO.java
src/main/java/com/mps/think/setup/vo/OrderAuxiliaryInformationVO.java
src/main/java/com/mps/think/setup/vo/OrderDeliveryOptionsVO.java
src/main/java/com/mps/think/setup/vo/OrderItemsVO.java
src/main/java/com/mps/think/setup/vo/OrderKeyInformationVO.java
src/main/java/com/mps/think/setup/vo/OrderVO.java
src/main/java/com/mps/think/setup/vo/PaymentBreakdownVO.java

Thw sprint 10 cs   add orders

---

src/main/java/com/mps/think/setup/controller/RateCardsController.java
src/main/java/com/mps/think/setup/controller/RateCardsRenewalsController.java
src/main/java/com/mps/think/setup/repo/RateCardsRepo.java
src/main/java/com/mps/think/setup/service/RateCardsService.java
src/main/java/com/mps/think/setup/serviceImpl/RateCardsServiceImpl.java

THT-212new

---

src/main/java/com/mps/think/setup/model/RateCards.java
src/main/java/com/mps/think/setup/vo/RateCardsVO.java

ocId mapping

---

src/main/java/com/mps/think/setup/model/CustomerCategory.java
src/main/java/com/mps/think/setup/serviceImpl/CustomerCategoryServiceImpl.java
src/main/java/com/mps/think/setup/vo/CustomerCategoryVO.java

added an extra field

---

src/main/java/com/mps/think/setup/controller/ProductInformationController.java
src/main/java/com/mps/think/setup/model/OrderItemDetails.java
src/main/java/com/mps/think/setup/model/OrderItems.java
src/main/java/com/mps/think/setup/model/PaymentBreakdown.java
src/main/java/com/mps/think/setup/model/ProductInformation.java
src/main/java/com/mps/think/setup/model/SourceCode.java
src/main/java/com/mps/think/setup/repo/ProductInformationRepo.java
src/main/java/com/mps/think/setup/service/ProductInformationService.java
src/main/java/com/mps/think/setup/serviceImpl/AddOrderServiceImpl.java
src/main/java/com/mps/think/setup/serviceImpl/ProductInformationServiceImpl.java
src/main/java/com/mps/think/setup/vo/OrderItemDetailsVO.java
src/main/java/com/mps/think/setup/vo/OrderItemsVO.java
src/main/java/com/mps/think/setup/vo/PaymentBreakdownVO.java
src/main/java/com/mps/think/setup/vo/ProductInformationVO.java
src/main/java/com/mps/think/setup/vo/SourceCodeVO.java

Reverts highwire/think-setup#384

Revert "Revert "Product order""

---

src/main/java/com/mps/think/setup/model/OrderCodesSuper.java
src/main/java/com/mps/think/setup/sorl/SolrDocumentController.java
src/main/java/com/mps/think/setup/vo/CustomerAddressesVO.java
src/main/java/com/mps/think/setup/vo/OrderAddressMappingVO.java
src/main/java/com/mps/think/setup/vo/OrderAuxiliaryInformationVO.java
src/main/java/com/mps/think/setup/vo/OrderClassVO.java
src/main/java/com/mps/think/setup/vo/OrderDeliveryOptionsVO.java
src/main/java/com/mps/think/setup/vo/OrderItemsVO.java
src/main/java/com/mps/think/setup/vo/OrderKeyInformationVO.java

Reverts highwire/think-setup#561

Revert "removed the redundant import from solrDocumentController"

---

src/main/java/com/mps/think/setup/model/OrderCodesSuper.java
src/main/java/com/mps/think/setup/sorl/SolrDocumentController.java
src/main/java/com/mps/think/setup/vo/CustomerAddressesVO.java
src/main/java/com/mps/think/setup/vo/OrderAddressMappingVO.java
src/main/java/com/mps/think/setup/vo/OrderAuxiliaryInformationVO.java
src/main/java/com/mps/think/setup/vo/OrderClassVO.java
src/main/java/com/mps/think/setup/vo/OrderDeliveryOptionsVO.java
src/main/java/com/mps/think/setup/vo/OrderItemsVO.java
src/main/java/com/mps/think/setup/vo/OrderKeyInformationVO.java

Reverts highwire/think-setup#562

Revert "Revert "removed the redundant import from solrDocumentController""
